from io import BytesIO
from flask import send_file
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate
from reportlab.platypus import Paragraph
from reportlab.platypus import Spacer
from flask import Blueprint, jsonify
from flask_jwt_extended import jwt_required, get_jwt_identity
from database import db
from models.company import Company
from models.carbon import CarbonRecord
from models.esg import ESGScore
from models.report import Report
from datetime import datetime


reports_bp = Blueprint("reports", __name__)



# Generate Sustainability Report

@reports_bp.route("/", methods=["POST"])
@jwt_required()
def generate_report():

    try:

        user_id = get_jwt_identity()

        company = Company.query.filter_by(
            user_id=user_id
        ).first()

        if not company:

            return jsonify({
                "success": False,
                "message": "Company not found"
            }), 404

        
        # Latest Carbon Record
        carbon = CarbonRecord.query.filter_by(
            company_id=company.id
        ).order_by(
            CarbonRecord.created_at.desc()
        ).first()

        esg = ESGScore.query.filter_by(
            company_id=company.id
        ).order_by(
            ESGScore.created_at.desc()
        ).first()

        if carbon is None or esg is None:
            return jsonify({
                "success": False,
                "message": "Please generate Carbon and ESG data first."
            }), 400

        business = carbon.business_input

        if business is None:
            return jsonify({
                "success": False,
                "message": "Business data not found."
            }), 404

        # Build Report
        
        report_content = f"""
==========================================================
               ECOFINANCE SL
        ESG SUSTAINABILITY REPORT
==========================================================

Company Name
------------
{company.company_name}

Business Sector
---------------
{company.business_sector}

Reporting Period
----------------
{business.reporting_month}/{business.reporting_year}

Grid Electricity
----------------
{business.grid_electricity_kwh} kWh

Renewable Electricity
---------------------
{business.renewable_electricity_kwh} kWh

Diesel
------
{business.diesel_liters} L

Petrol
------
{business.petrol_liters} L

LPG
---
{business.lpg_kg} kg

Natural Gas
-----------
{business.natural_gas_m3} m³

Business Travel
---------------
{business.business_travel_km} km

Employee Travel
---------------
{business.employee_travel_km} km

Freight Transport
-----------------
{business.freight_transport_km} km

General Waste
-------------
{business.general_waste_kg} kg

Recycled Waste
--------------
{business.recycled_waste_kg} kg

Hazardous Waste
---------------
{business.hazardous_waste_kg} kg


==========================================================
CARBON FOOTPRINT
==========================================================

Scope 1 : {carbon.scope1:.2f} kg CO₂e

Scope 2 : {carbon.scope2:.2f} kg CO₂e

Scope 3 : {carbon.scope3:.2f} kg CO₂e

Total Emission : {carbon.total_emission:.2f} kg CO₂e

==========================================================
ENVIRONMENTAL
==========================================================

Score : {esg.environmental_score}

Status : {esg.environmental_status}

Remark :
{esg.environmental_remark}


==========================================================
SOCIAL
==========================================================

Score : {esg.social_score}

Status : {esg.social_status}

Remark :
{esg.social_remark}


==========================================================
GOVERNANCE
==========================================================

Score : {esg.governance_score}

Status : {esg.governance_status}

Remark :
{esg.governance_remark}


==========================================================
OVERALL ESG
==========================================================

Overall Score : {esg.overall_score}

Status : {esg.overall_status}

Remark :
{esg.overall_remark}


==========================================================
RECOMMENDATIONS
==========================================================

{esg.recommendations}

==========================================================
Generated by EcoFinance SL
Generated on: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
==========================================================
"""
        
        # Save Report
        report = Report(
            company_id=company.id,
            report_title="Sustainability Report",
            report_type="FULL_REPORT",
            report_content=report_content,
            report_status="Generated"
        )

        db.session.add(report)

        db.session.commit()

        return jsonify({

            "success": True,
            "message": "Report generated successfully.",

            "data": {

                "id": report.id,
                "title": report.report_title,
                "type": report.report_type,
                "status": report.report_status,
                "generated_at": report.generated_at.strftime("%Y-%m-%d %H:%M:%S")

            }

        }), 201

    except Exception as e:

        db.session.rollback()

        return jsonify({

            "success": False,

            "message": str(e)

        }), 500
    

# Get All Reports
@reports_bp.route("/", methods=["GET"])
@jwt_required()
def get_reports():

    try:

        user_id = get_jwt_identity()

        company = Company.query.filter_by(
            user_id=user_id
        ).first()

        if company is None:

            return jsonify({
                "success": False,
                "message": "Company not found"
            }), 404

        reports = Report.query.filter_by(
            company_id=company.id
        ).order_by(
            Report.generated_at.desc()
        ).all()

        data = []

        for report in reports:

            data.append({

                "id": report.id,
                "title": report.report_title,
                "type": report.report_type,
                "status": report.report_status,
                "content": report.report_content,
                "generated_at": report.generated_at.strftime("%Y-%m-%d %H:%M:%S")

            })

        return jsonify({

            "success": True,

            "data": data

        }), 200

    except Exception as e:

        return jsonify({

            "success": False,

            "message": str(e)

        }), 500


# Get Single Report
@reports_bp.route("/<int:report_id>", methods=["GET"])
@jwt_required()
def get_report(report_id):

    try:

        user_id = get_jwt_identity()

        company = Company.query.filter_by(
            user_id=user_id
        ).first()

        if company is None:

            return jsonify({
                "success": False,
                "message": "Company not found"
            }), 404

        report = Report.query.filter_by(

            id=report_id,
            company_id=company.id

        ).first()

        if report is None:

            return jsonify({

                "success": False,
                "message": "Report not found"

            }), 404

        return jsonify({

            "success": True,

            "data": {

                "id": report.id,
                "title": report.report_title,
                "type": report.report_type,
                "status": report.report_status,
                "content": report.report_content,
                "generated_at": report.generated_at.strftime("%Y-%m-%d %H:%M:%S")
                
            }

        }), 200

    except Exception as e:

        return jsonify({

            "success": False,

            "message": str(e)

        }), 500



# Delete Report
@reports_bp.route("/<int:report_id>", methods=["DELETE"])
@jwt_required()
def delete_report(report_id):

    try:

        user_id = get_jwt_identity()

        company = Company.query.filter_by(
            user_id=user_id
        ).first()

        if company is None:

            return jsonify({

                "success": False,
                "message": "Company not found"

            }), 404

        report = Report.query.filter_by(

            id=report_id,
            company_id=company.id

        ).first()

        if report is None:

            return jsonify({

                "success": False,
                "message": "Report not found"

            }), 404

        db.session.delete(report)

        db.session.commit()

        return jsonify({

            "success": True,
            "message": "Report deleted successfully."

        }), 200

    except Exception as e:

        db.session.rollback()

        return jsonify({

            "success": False,
            "message": str(e)

        }), 500
    


# Download Report PDF
@reports_bp.route("/download/<int:report_id>", methods=["GET"])
@jwt_required()
def download_report(report_id):

    try:

        user_id = get_jwt_identity()

        company = Company.query.filter_by(
            user_id=user_id
        ).first()

        if company is None:

            return jsonify({
                "success": False,
                "message": "Company not found"
            }), 404

        report = Report.query.filter_by(
            id=report_id,
            company_id=company.id
        ).first()

        if report is None:

            return jsonify({
                "success": False,
                "message": "Report not found"
            }), 404

        buffer = BytesIO()

        document = SimpleDocTemplate(buffer)

        styles = getSampleStyleSheet()

        story = []

        story.append(Paragraph("<b>EcoFinance SL</b>", styles["Title"]))

        story.append(Paragraph(
            "ESG Sustainability Report",
            styles["Heading1"]
        ))

        story.append(Spacer(1, 20))

        story.append(Paragraph(
            f"<b>Company:</b> {company.company_name}",
            styles["Normal"]
        ))

        story.append(Paragraph(
            f"<b>Report:</b> {report.report_title}",
            styles["Normal"]
        ))

        story.append(Paragraph(
            f"<b>Type:</b> {report.report_type}",
            styles["Normal"]
        ))

        story.append(Paragraph(
            f"<b>Date:</b> {report.generated_at.strftime('%Y-%m-%d %H:%M:%S')}",
            styles["Normal"]
        ))

        story.append(Spacer(1, 20))

        story.append(Paragraph(
            "<b>Report Details</b>",
            styles["Heading2"]
        ))

        story.append(Paragraph(
            report.report_content.replace("\n", "<br/>"),
            styles["BodyText"]
        ))

        document.build(story)

        buffer.seek(0)

        return send_file(

            buffer,

            as_attachment=True,
            download_name=f"Report_{report.id}.pdf",
            mimetype="application/pdf"

        )

    except Exception as e:

        return jsonify({

            "success": False,
            "message": str(e)

        }), 500