"""Initial schema

Revision ID: 1349df535e28
Revises: 
Create Date: 2026-07-25 22:27:23.561290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1349df535e28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('business_sector', sa.String(length=150), nullable=True),
    sa.Column('registration_no', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('contact_no', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('reporting_year', sa.Integer(), nullable=False),
    sa.Column('reporting_month', sa.Integer(), nullable=False),
    sa.Column('grid_electricity_kwh', sa.Float(), nullable=True),
    sa.Column('renewable_electricity_kwh', sa.Float(), nullable=True),
    sa.Column('diesel_liters', sa.Float(), nullable=True),
    sa.Column('petrol_liters', sa.Float(), nullable=True),
    sa.Column('lpg_kg', sa.Float(), nullable=True),
    sa.Column('natural_gas_m3', sa.Float(), nullable=True),
    sa.Column('business_travel_km', sa.Float(), nullable=True),
    sa.Column('employee_travel_km', sa.Float(), nullable=True),
    sa.Column('freight_transport_km', sa.Float(), nullable=True),
    sa.Column('general_waste_kg', sa.Float(), nullable=True),
    sa.Column('recycled_waste_kg', sa.Float(), nullable=True),
    sa.Column('hazardous_waste_kg', sa.Float(), nullable=True),
    sa.Column('total_carbon', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('esg_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('renewable_energy', sa.Float(), nullable=True),
    sa.Column('water_consumption', sa.Float(), nullable=True),
    sa.Column('recycling_rate', sa.Float(), nullable=True),
    sa.Column('environmental_policy', sa.Boolean(), nullable=True),
    sa.Column('employee_satisfaction', sa.Float(), nullable=True),
    sa.Column('training_hours', sa.Float(), nullable=True),
    sa.Column('gender_diversity', sa.Float(), nullable=True),
    sa.Column('community_projects', sa.Boolean(), nullable=True),
    sa.Column('board_meetings', sa.Integer(), nullable=True),
    sa.Column('ethics_policy', sa.Boolean(), nullable=True),
    sa.Column('compliance', sa.Boolean(), nullable=True),
    sa.Column('risk_management', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('esg_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('environmental_score', sa.Float(), nullable=False),
    sa.Column('social_score', sa.Float(), nullable=False),
    sa.Column('governance_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('environmental_status', sa.String(length=50), nullable=True),
    sa.Column('social_status', sa.String(length=50), nullable=True),
    sa.Column('governance_status', sa.String(length=50), nullable=True),
    sa.Column('overall_status', sa.String(length=50), nullable=True),
    sa.Column('environmental_remark', sa.Text(), nullable=True),
    sa.Column('social_remark', sa.Text(), nullable=True),
    sa.Column('governance_remark', sa.Text(), nullable=True),
    sa.Column('overall_remark', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('report_title', sa.String(length=200), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('report_content', sa.Text(), nullable=False),
    sa.Column('report_status', sa.String(length=50), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carbon_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_input_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('scope1', sa.Float(), nullable=True),
    sa.Column('scope2', sa.Float(), nullable=True),
    sa.Column('scope3', sa.Float(), nullable=True),
    sa.Column('total_emission', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_input_id'], ['business_inputs.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carbon_records')
    op.drop_table('reports')
    op.drop_table('esg_scores')
    op.drop_table('esg_inputs')
    op.drop_table('business_inputs')
    op.drop_table('companies')
    op.drop_table('users')
    # ### end Alembic commands ###
