"""Add ESG foreign keys

Revision ID: 927d33da7926
Revises: 1349df535e28
Create Date: 2026-07-25 23:39:17.748369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927d33da7926'
down_revision = '1349df535e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('esg_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('esg_input_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('carbon_record_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'carbon_records', ['carbon_record_id'], ['id'])
        batch_op.create_foreign_key(None, 'esg_inputs', ['esg_input_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('esg_scores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('carbon_record_id')
        batch_op.drop_column('esg_input_id')

    # ### end Alembic commands ###
