"""Update carbon model

Revision ID: a75970fdb74e
Revises: 927d33da7926
Create Date: 2026-07-26 00:00:46.505497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a75970fdb74e'
down_revision = '927d33da7926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carbon_records', schema=None) as batch_op:
        batch_op.alter_column('scope1',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('scope2',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('scope3',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('total_emission',
               existing_type=mysql.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carbon_records', schema=None) as batch_op:
        batch_op.alter_column('total_emission',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('scope3',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('scope2',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('scope1',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
